site_name: Verilog Fun
site_url: https://www.verilog.fun
nav:
    - 主页: index.md
    - 计算机组成原理研讨课: 
      - 前言: pocc.md
      - 课程信息: pocc/course-information.md
      - 第一周：Logisim 入门: pocc/week1-logisim-intro.md
      - 第二周：运算器设计: pocc/week2-calculator-design.md
      - 第三周：Verilog 入门: pocc/week3-verilog-intro.md
      - 外部资料: pocc/ext-res.md
    - Logisim:
      - logisim.md
      - Logisim 实用技巧: logisim/logisim-practical-tips.md
      - Logisim 的 JAVA 环境配置: logisim/logisim-java-environment-configuration.md
    - Verilog:
      - verilog.md
      - Verilog 学习资料: verilog/verilog-study-materials.md
      - Icarus Verilog for Windows: verilog/verilog-windows.md
      - iverilog + GTKWave 环境搭建: verilog/iverilog-gtkwave-environment-installation-usage.md
      - 如何生成原理图: verilog/how-to-generate-schematics.md
    - VOJ: https://oj.verilog.fun:23536

copyright: Copyright &copy; 2022 - 2024 Verilog Fun

theme:
  language: zh
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    # - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    # - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  # palette:
  #   - media: "(prefers-color-scheme)"
  #     toggle:
  #       icon: material/link
  #       name: Switch to light mode
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     primary: indigo
  #     accent: indigo
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to dark mode
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     primary: black
  #     accent: indigo
  #     toggle:
  #       icon: material/toggle-switch-off
  #       name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  menu:

  icon:
    logo: verilog-oj
# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Hooks
# hooks:
#   - material/overrides/hooks/shortcodes.py
#   - material/overrides/hooks/translations.py

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
    extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/verilog-oj
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.smartsymbols
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.superfences
  # - pymdownx.tabbed:
  #     alternate_style: true
  #     combine_header_slug: true
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify
  #       kwds:
  #         case: lower
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  - pymdownx.tilde
